from litestar.dto import DataclassDTO, DTOConfig

from person.models import Person


class ReadPersonDTO(DataclassDTO[Person]):
    # Exclude email and the street field of the nested address
    config = DTOConfig(
        # exclude the email and address of the all the parent and children
        exclude={"email", "address.street", "children.0.email", "children.0.address"},
        rename_fields={"address.zip_code": "postal_code"}, # rename zip_code to postal_code in the output
        # set max_nested_depth to 2 to allow for the children field to be included in the output 
        # but not any further nesting of children (eg. grandchildren)
        max_nested_depth=1 
    )
    

class WritePersonDTO(DataclassDTO[Person]):
    # Exclude the id field when creating a new person, since it will be generated by the database
    # Also exclude the children field and the address field, 
    # since we want to create those separately and link them to the person after the person is created
    config = DTOConfig(exclude={"id", "address", "children"}, partial=True)